/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import EDD.Grafos;
import static EDD.Grafos.contarLineasHastaRelaciones;
import static Interfaz.Ventana2.id2;
import archivos.Archivos;
import static archivos.Archivos.agregarRelacion;
import static archivos.Archivos.concatenarUsuarios;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tomas
 */
public class Ventana4 extends javax.swing.JFrame {

    public static String idpersonal = "";
    public static String idamistad = "";
    public static String tiempo = "";
    public static String uss = "";
    
    public static Ventana2 v2;
    /**
     * Creates new form Ventana1
     * @param v2
     */

    public static Ventana5 v5;
    /**
     * Creates new form Ventana1
     * @param v5
     */
    
    public Ventana4(Ventana2 v2) {
        initComponents();
        Ventana4.v2 = v2;
        v2.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        String idper = id2;
        idperso.setText(idper);
        String uss = concatenarUsuarios("test\\txt\\textox.txt");
        usuarios.setText(uss);
                
    }
    
    public Ventana4(Ventana5 v5) {
        initComponents();
        Ventana4.v5 = v5;
        v5.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        String idper = id2;
        idperso.setText(idper);
        String uss = concatenarUsuarios("test\\txt\\textox.txt");
        usuarios.setText(uss);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usuarios = new javax.swing.JTextArea();
        next = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        time = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idperso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idamis1 = new javax.swing.JTextField();
        mr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarios.setColumns(20);
        usuarios.setRows(5);
        jScrollPane1.setViewportView(usuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 240, 120));

        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 100, -1));

        exit.setBackground(new java.awt.Color(255, 102, 102));
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 10, 40, -1));

        time.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tiempo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relación de amistad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, -1));

        idperso.setForeground(new java.awt.Color(0, 0, 0));
        idperso.setText("xxx");
        jPanel1.add(idperso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID amistad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID personal:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        idamis1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(idamis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, 20));

        mr.setText("Mostrar Relaciones ");
        mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrActionPerformed(evt);
            }
        });
        jPanel1.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Ventana4.idpersonal = idperso.getText();
        Ventana4.idamistad = idamis1.getText();
        Ventana4.tiempo = time.getText();
        
        Archivos usuarios = new Archivos();
        
        int idp = Integer.parseInt(idpersonal);
        int ida = Integer.parseInt(idamistad);
        int t = Integer.parseInt(tiempo);

        agregarRelacion("test\\txt\\textox.txt", idp, ida, t);
        
        Ventana5 v5= new Ventana5(this); 
    }//GEN-LAST:event_nextActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrActionPerformed
        try {
            int numVertices = contarLineasHastaRelaciones("test\\txt\\textox.txt");
            Grafos grafo = new Grafos(numVertices);
            String textox = "test\\txt\\textox.txt";
            grafo.leerArchivo(textox);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventana5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4(v2).setVisible(true);
                new Ventana4(v5).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTextField idamis1;
    private javax.swing.JLabel idperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mr;
    private javax.swing.JButton next;
    private javax.swing.JTextField time;
    private javax.swing.JTextArea usuarios;
    // End of variables declaration//GEN-END:variables
}
